name: Check reviews

on:
  pull_request_review:
    types: [dismissed, submitted]

permissions:
  contents: read
  pull-requests: write

jobs:
  check_reviews:
    name: Check reviews
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check reviews
        id: check-reviews
        uses: ./
        with:
          reviewers_file: .reviewers.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
