name: Set reviewers

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - review_requested
      - review_request_removed

permissions:
  contents: read
  pull-requests: write

jobs:
  set_reviewers:
    name: Set reviewers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Set reviewers
        uses: ./
        with:
          reviewers_file: .reviewers.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ github.event.pull_request.number }}
          set_reviewers: true
